"""empty message

Revision ID: 25aefa751f8e
Revises: 78934e2cc19d
Create Date: 2019-11-05 20:15:56.300061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25aefa751f8e'
down_revision = '78934e2cc19d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
