"""empty message

Revision ID: 32592a4dd663
Revises: 06e3c045a4e9
Create Date: 2019-12-07 19:50:55.385874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32592a4dd663'
down_revision = '06e3c045a4e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pref_language', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pref_language')
    # ### end Alembic commands ###
