SECRET_KEY: something
MESSAGES_DIR: ../messages
DB_URI: mysql://localhost/watchTranslations
DBCONFIG_FILE: replica.my.cnf
STATIC_URL: /static/
APPLICATION_ROOT: /
CONSUMER_KEY: dbfe50bb312d4b501e8f9d82985b2073
CONSUMER_SECRET: e552f59d5bd8048cd1250109bbd7d8ecb7216fe1
OAUTH_MWURI: https://meta.wikimedia.org/w
DEBUG: True
SMTP_HOST: hostname
SMTP_AUTH: False
SMTP_USERNAME: username
SMTP_PASSWORD: password
CONTACT_EMAIL: webmaster@example.com
FROM_EMAIL: no-reply@example.com
PROJECT_URI: http://localhost:5000/
